version: '3.8'

# Production overrides for docker-compose.yml
services:
  # Go Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      DB_HOST: staging-jan-4-2023-cluster.cluster-cylpew54lkmg.eu-west-1.rds.amazonaws.com
      DB_PORT: 3306
      DB_NAME: sc_voucher
      DB_USER: sc_voucher_dbuser
      DB_PASSWORD: ${DB_PASSWORD:-fOGYrE$$TEND!uNcen^dIVeN}
      PORT: 3001
    ports:
      - "3001:3001"
    networks:
      - voucher-network
    restart: unless-stopped

  # React Frontend with Nginx
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - voucher-network
    restart: unless-stopped

# Using external MySQL database - no local volumes needed

networks:
  voucher-network:
    driver: bridge